### ISSUE TITLE
Inquiry on the Release Date of Code and Synthesized Dataset

### ISSUE THREAD

**Issue by YesianRohn** [cuijl-ai/TextNeRF#1]
Hi, great work! Could you please let us know when the code and synthesized dataset will be released? Thanks!

**Comment by cuijl-ai** [comment]
Hi, thank you for your interest. The dataset can be accessed via the Google Drive link mentioned in the README. Regarding the code, we apologize, but we are currently unable to make it public due to certain reasons, as some of our methods are used in pending patents.

**Comment by YesianRohn** [comment]
get it, thanks!
